object Dependencies {
    const val kotlin_version = "1.5.21"
    const val gradle_version = "7.0.1"
    const val gms_version = "4.3.10"
    const val firebase_version = "2.7.1"
    const val appcompat_version = "1.3.1"
    const val constraint_layout_version = "2.1.0"
    const val core_ktx_version = "1.6.0"
    const val material_version = "1.4.0"
    const val retrofit_version = "2.9.0"
    const val legacy_version = "1.0.0"
    const val kotlinx_version = "1.2.2"
    const val gson_version = "2.8.8"
    const val firebase_bom_version = "28.4.0"
    const val preference_version = "1.1.1"
    const val lifecycle_version = "2.3.1"
}
