name: "Attendance Build"
on: push
jobs:
  setup-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: ./gradlew assembleDebug
    - uses: actions/upload-artifact@master
      with:
        name: Attendance Debug APK
        path: app/build/outputs/apk/debug/TSG-Attendance-debug-1.0.apk
